<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/admin">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->

        <li class='<?php if($this->data["activeLink"] == 'clients'){echo("active");}?>' ><a class=" active" href="<?='/admin/clients'?>">Clients</a></li>

        <li class='<?php if($this->data["activeLink"] == 'bills'){echo("active");}?>' ><a href="<?='/admin/bills'?>">Bills</a></li>

        <li class='<?php if($this->data["activeLink"] == 'articles'){echo("active");}?>' ><a href="<?='/admin/articles'?>">Articles</a></li>

        <li><a href="<?='/admin/logout'?>">Log Out</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>