<?php
if (isset($this->data['bills'])){
    $len = count($this->data['bills']);
    if ($len > 0){ 
?>

    <table class="table table-striped">
        <h1 class='text-info'>Factures Nulles</h1>
        <thead>
            <tr class='active'>
                <th>ID</th>
                <th>name</th>
                <th>Quantity</th>
                <th>msrp</th>
            </tr>
        </thead>

        <tbody>

            <?php  
            $len = count($this->data['bills']);
            $bills = $this->data['bills'];
            for($i=0; $i < $len; $i++){ ?>
                
                <?php $bill = $bills[$i]; ?>

                <tr class="bg-success">
                        
                      
                        
                        <td><?= $bill['id']   			?></td>
                        <td><?= $bill['name'] 	     	?></td>
                        <td><?= $bill['quantity']  	    ?></td>
                        <td><?= $bill['msrp']			?></td>
                </tr>
            
            <?php } ?>
        </tbody>
    </table>

<?php 
    }else{
?>      <p class="alert alert-warning">Vous n'avez aucune facture.</p>
<?php    }
}



?>