<body>
    <section>

        <?php 
        $details = $this->data['billdetail'];
        if(isset($details) && count($details) > 0){?>
<!--             <h1><?= var_dump($details);?></h1> -->
            <h2><?= $details[0]['firstname'] ?></h2>
            <h3><?= $details[0]['lastname'] ?></h3>
            <h3><?= $details[0]['address'] ?></h3>
            <p><?=  $details[0]['siret'] ?></p>
            <p><?=  $details[0]['phone'] ?></p>
            <p><?=  $details[0]['mail'] ?></p>
            <hr />
            <caption>Facture n° <?= $_GET['id']?> </caption>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Bill ID</th>
                    <th>Product Name</th>
                    <th>Ordered Qty</th>
                    <th>Unit price</th>
                    <th>Total</th>
                </tr>
            </thead>
            
            <tbody>
                <?php $totalHT = 0; ?>
                <?php for($i=0; $i < count($details); $i++){ ?>
                    
                    <?php $detail = $details[$i];
                        $totalHT += $detail['msrp'] * $detail['ordered_quantity']; 
                    ?>
                    <tr>
                            <td><?= $detail['bill_id_fk']     ?></td>  
                            <td><?= $detail['name']           ?></td>
                            <td><?= $detail['ordered_quantity']     ?></td>
                            <td><?= $detail['msrp']       ?></td>
                            <td><?= $detail['msrp'] * $detail['ordered_quantity'].'€' ?></td>
                    </tr>

                <?php } ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>Montant HT</th>
                    <td><?= $totalHT.'€'?></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>TVA</th>
                    <td><?php $TVA = $totalHT * (20/100); echo ROUND($TVA,2).'€'; ?></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>Montant TTC</th>
                    <td><?= ROUND($totalHT + $TVA,2).'€'?></td>
                </tr>
            </tbody>
        </table>
        <?php } ?>
    </section>
</body>
</html>