<?php 
// $isDev = true;
// if(isDev){ ?>

<h1>Choisis ta ponction.</h1>
<form method='post' action="/paid">
	<button name="mastercard"><img src="<?= ASSETS_PATH ?>images/payment/mastercard.png"></img></button>
	<button name="paypal"><img src="<?= ASSETS_PATH ?>images/payment/paypal.png"></img></button>
	<button name="visa"><img src="<?= ASSETS_PATH ?>images/payment/visa.png"></img></button>
</form>

<?php 
// } 
?>