<head>
	<title><?= $this->data['title']?></title>
	<script src="<?= ASSETS_PATH ?>js/jquery-3.1.0.js"></script>
	<script src="<?= ASSETS_PATH ?>js/script.js"> </script>
	<script src="<?= ASSETS_PATH ?>js/classes/Cart.js"> </script>
	<meta charset="utf-8" />
	<link rel="stylesheet" type="text/css" href="<?= ASSETS_PATH ?>css/style.css">
	<link rel="stylesheet" type="text/css" href="<?= ASSETS_PATH ?>css/cart.css">
	
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel='stylesheet' type='text/css' /> -->
	<!-- Latest compiled and minified CSS -->

	<link rel="stylesheet" href="<?= ASSETS_PATH ?>css/bootstrap.min.css">

	<!-- Optional theme -->

	<link rel="stylesheet" href="<?= ASSETS_PATH ?>css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->

	<script src="<?= ASSETS_PATH ?>js/bootstrap.min.js" crossorigin="anonymous"></script>
</head>