<form action="/register" method="post">
	<p>Identifiant : 
		<input placeholder="votre identifiant" 
				name="email" 
				type="email" 
				method="post" 
				required>
	</p>




 	<p>Mot de passe : 
 		<input placeholder="votre mot de passe" 
 		name="password" 
 		type="password" 
 		method="post" 
 		required></p>
 	
 	<p>Confirmez vote Mot de passe : 
 		<input placeholder="votre mot de passe" 
 		name="confirmpassword" 
 		type="password" 
 		method="post" 
 		required></p>

 	<button type="submit">ok</button>
</form>